version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/IF"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/adventure-support"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_14"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_15"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_16_1"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_16_2-3"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_16_4-5"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_17_0"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_17_1"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_18_0"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_18_1"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_18_2"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_19_0"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_19_1"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_19_2"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_19_3"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_19_4"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_20_0"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_20_1"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_20_2"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_20_3-4"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_20_5"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_20_6"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_21_0"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_21_1"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/1_21_2-3"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/nms/abstraction"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/inventory-view/iv-abstract-class"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/inventory-view/iv-abstraction"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/inventory-view/iv-interface"
    schedule:
      interval: "daily"
